# Generated by Django 3.1 on 2020-12-06 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProPlayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matches',
            field=models.IntegerField(default=0, help_text='Entre o numero de partidas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='victories',
            field=models.IntegerField(default=0, help_text='Entre o numero de vitorias'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='birthday',
            field=models.DateField(help_text='Entre a data de aniversário'),
        ),
        migrations.AlterField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(help_text='Entre os jogos jogados', to='ProPlayer.Game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(help_text='Entre o nome', max_length=100, verbose_name='Real Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(help_text='Entre o time', on_delete=django.db.models.deletion.CASCADE, to='ProPlayer.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(help_text='Entre o nome de usuário', max_length=100, verbose_name='Username'),
        ),
    ]
